
workflows:
  android-release:
    name: Android Release AAB
    max_build_duration: 60

    environment:
      flutter: stable
      groups:
        - keystore_credentials

    scripts:
      - name: Generate Android platform (create /android if missing)
        script: |
          flutter --version
          flutter create --platforms=android --org com.chess.positional.master .

      - name: Flutter pub get
        script: flutter pub get

      - name: Flutter analyze (fail fast)
        script: flutter analyze lib --fatal-infos --fatal-warnings

      - name: Build appbundle (release)
        script: flutter build appbundle --release -v

    artifacts:
      - build/app/outputs/bundle/release/*.aab

    # Optional publishing to Google Play (cuando tengas la credencial JSON):
    # publishing:
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: internal
