
workflows:
  android-release:
    name: Android Release AAB (auto-add android, sanity checked)
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - keystore_credentials
    scripts:
      - name: Ensure Android platform (generate /android if missing)
        script: |
          flutter --version
          flutter create --platforms=android --org com.chess.positional.master .
      - name: Sanity check & auto-patch dot-shorthands
        script: |
          set -e
          echo "HEAD commit:"; git rev-parse HEAD
          echo "Latest commit:"; git log -1 --pretty="format:%h %ci %s"
          echo "First 60 lines of lib/main.dart:"; sed -n '1,60p' lib/main.dart || true
          echo "Searching for '.fromSeed(' across lib/..."
          if grep -R "\.fromSeed(" -n lib; then
            echo "FOUND experimental '.fromSeed(' — patching to 'ColorScheme.fromSeed('";
            sed -i.bak 's/\.fromSeed(/ColorScheme.fromSeed(/g' $(grep -R "\.fromSeed(" -l lib) || true
          else
            echo "OK: no dot-shorthands found."
          fi
      - name: Clean cache & pub get
        script: |
          rm -rf build .dart_tool
          flutter pub get
      - name: Flutter analyze (fail fast)
        script: flutter analyze --fatal-infos --fatal-warnings
      - name: Build appbundle (release)
        script: flutter build appbundle --release -v
    artifacts:
      - build/app/outputs/bundle/release/*.aab
