
workflows:
  android-release:
    name: Android Release AAB
    max_build_duration: 60

    environment:
      flutter: stable
      groups:
        - keystore_credentials     # sube aquí tu .jks + variables (alias/contraseñas)

    scripts:
      - name: Generate Android platform (create /android if missing)
        script: |
          flutter --version
          flutter create --platforms=android --org com.chess.positional.master .

      - name: Flutter pub get
        script: flutter pub get

      # Analiza solo lib/, y SIEMPRE devuelve 0 aunque haya infos/warnings (|| true)
      - name: Flutter analyze (non-blocking)
        script: |
          flutter analyze lib || true

      - name: Build appbundle (release)
        script: flutter build appbundle --release -v

    artifacts:
      - build/app/outputs/bundle/release/*.aab

    # Publicación opcional a Google Play (cuando tengas la credencial JSON):
    # publishing:
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: internal
