
workflows:
  android-release:
    name: Android Release AAB
    max_build_duration: 60

    environment:
      flutter: stable
      groups:
        - keystore_credentials     # sube aquí tu .jks + variables (alias / contraseñas)

    scripts:
      - name: Generate Android platform (create /android if missing)
        script: |
          flutter --version
          flutter create --platforms=android --org com.chess.positional.master .

      - name: Flutter pub get
        script: flutter pub get

      # 👇 Quitar flags fatales para que 'info/warning' NO paren el build
      - name: Flutter analyze (non-fatal)
        script: flutter analyze lib

      - name: Build appbundle (release)
        script: flutter build appbundle --release -v

    artifacts:
      - build/app/outputs/bundle/release/*.aab

    # Publicación opcional a Google Play (cuando tengas las credenciales):
    # publishing:
    #   google_play:
    #     credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #     track: internal
